const Data={
    video:[
        {
            id:1,
            title:"React JS Crash Course",
            views:1000,
            category:"Education",
            thumbnail:"https://img.youtube.com/vi/sBws8MSXN7A/maxresdefault.jpg",
            videoUrl:"https://www.youtube.com/watch?v=sBws8MSXN7A",
            userId:1,
        },
           {
        id: 2,
        title: "React Tutorial for Beginners",    
        views: 1500000,
        category: "Education",
        thumbnail: "https://img.youtube.com/vi/QFaFIcGhPoM/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/watch?v=QFaFIcGhPoM",
        userId: 2,
    },
    {
        id: 3,
        title: "React Native Crash Course",      
        views: 1800000,
        category: "Education",
        thumbnail: "https://img.youtube.com/vi/0-S5a0eXPoc/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/watch?v=0-S5a0eXPoc",
        userId: 3,
    },
    {
        id: 4,
        title: "React JS Full Course – Beginners to Advanced",
       
        views: 900000,
        category: "Education",
        thumbnail: "https://img.youtube.com/vi/x4rFhThSX04/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/watch?v=x4rFhThSX04",
        userId: 4,
    },
    {
        id: 5,
        title: "React JS Tutorial for Beginners",
        views: 850000,
        category: "Education",
        thumbnail: "https://img.youtube.com/vi/x4rFhThSX04/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/watch?v=x4rFhThSX04",
        userId: 5,
    },
    {
        id: 6,
        title: "React JS Intro & Setup",
        
        views: 720000,
        category: "Education",
        thumbnail: "https://img.youtube.com/vi/SqcY0GlETPk/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/watch?v=SqcY0GlETPk",
        userId: 6,
    },
    {
        id: 7,
        title: "React Tutorial #1 – Introduction",

        views: 500000,
        category: "Education",
        thumbnail: "https://img.youtube.com/vi/QFaFIcGhPoM/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/watch?v=QFaFIcGhPoM",
        userId: 7,
    },
    {
        id: 8,
        title: "React 18 Full Course",
       
        views: 640000,
        category: "Education",
        thumbnail: "https://img.youtube.com/vi/TtPXvEcE11E/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/watch?v=TtPXvEcE11E",
        userId: 8,
    },
    {
        id: 9,
        title: "React Hooks Tutorial",
       
        views: 580000,
        category: "Education",
        thumbnail: "https://img.youtube.com/vi/LlvBzyy-558/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/watch?v=LlvBzyy-558",
        userId: 9,
    },
    {
        id: 10,
        title: "React Router v6 Crash Course",
        views: 620000,
        category: "Education",
        thumbnail: "https://img.youtube.com/vi/0cSVuySEB0o/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/watch?v=0cSVuySEB0o",
        userId: 10,
    }
    ],
  user:[
    {
    id: 1,
    name: "Dhanush Kumar",
    email: "dhanushkumar@example.com",
    profilePicture: "https://randomuser.me/api/portraits/men/1.jpg",
    password: "password123",
  },
  {
    id: 2,
    name: "Aarav Patel",
    email: "aarav.patel@example.com",
    profilePicture: "https://randomuser.me/api/portraits/men/2.jpg",
    password: "securePass456",
  },
  {
    id: 3,
    name: "Riya Sharma",
    email: "riya.sharma@example.com",
    profilePicture: "https://randomuser.me/api/portraits/women/3.jpg",
    password: "myPass789",
  },
  {
    id: 4,
    name: "Neha Gupta",
    email: "neha.gupta@example.com",
    profilePicture: "https://randomuser.me/api/portraits/women/4.jpg",
    password: "helloWorld101",
  },
  {
    id: 5,
    name: "Karan Singh",
    email: "karan.singh@example.com",
    profilePicture: "https://randomuser.me/api/portraits/men/5.jpg",
    password: "qwerty123!",
  },
  {
    id: 6,
    name: "Priya Verma",
    email: "priya.verma@example.com",
    profilePicture: "https://randomuser.me/api/portraits/women/6.jpg",
    password: "verma2025",
  },
  {
    id: 7,
    name: "Rahul Das",
    email: "rahul.das@example.com",
    profilePicture: "https://randomuser.me/api/portraits/men/7.jpg",
    password: "dasSecure789",
  },
  {
    id: 8,
    name: "Sana Khan",
    email: "sana.khan@example.com",
    profilePicture: "https://randomuser.me/api/portraits/women/8.jpg",
    password: "khanPass321",
  },
  {
    id: 9,
    name: "Vikram Rao",
    email: "vikram.rao@example.com",
    profilePicture: "https://randomuser.me/api/portraits/men/9.jpg",
    password: "rao!Pass2026",
  },
  {
    id: 10,
    name: "Anjali Mehta",
    email: "anjali.mehta@example.com",
    profilePicture: "https://randomuser.me/api/portraits/women/10.jpg",
    password: "anjaliM123",
  },
  {
    id: 11,
    name: "Dev Malhotra",
    email: "dev.malhotra@example.com",
    profilePicture: "https://randomuser.me/api/portraits/men/11.jpg",
    password: "devPass890",
  },
  {
    id: 12,
    name: "Isha Rao",
    email: "isha.rao@example.com",
    profilePicture: "https://randomuser.me/api/portraits/women/12.jpg",
    password: "ishaR!234",
  }
  ]
}

export default Data 